# Generated by Django 5.2.7 on 2025-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated focus keywords', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Content generated by AI'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='S3 URL of associated video', max_length=500, null=True),
        ),
    ]
