# Generated by Django 5.2.7 on 2025-10-23 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Generated content title', max_length=300)),
                ('topic', models.CharField(help_text='Main topic/subject', max_length=200)),
                ('category', models.CharField(help_text='Content category', max_length=50)),
                ('unique_id', models.CharField(help_text='Unique identifier for content', max_length=100, unique=True)),
                ('video_id', models.CharField(blank=True, help_text='Sora video ID', max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='S3 video URL', max_length=500, null=True)),
                ('video_prompt', models.TextField(blank=True, help_text='Sora video generation prompt')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Content tags')),
                ('focus_keywords', models.JSONField(default=list, help_text='SEO focus keywords')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether content was published')),
                ('topic_keywords', models.JSONField(default=list, help_text='Extracted topic keywords for similarity detection')),
                ('category_usage_count', models.PositiveIntegerField(default=0, help_text='How many times this category was used recently')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['category'], name='sora_genera_categor_6bd9d6_idx'), models.Index(fields=['generated_at'], name='sora_genera_generat_ffbded_idx'), models.Index(fields=['topic'], name='sora_genera_topic_fc8e90_idx')],
            },
        ),
    ]
